# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 00:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wellcom_app', '0002_usage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
    ]
