# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wellcom_app', '0007_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_int_seconds', models.IntegerField()),
                ('temp_readings', models.TextField()),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wellcom_app.Well')),
            ],
        ),
        migrations.AlterField(
            model_name='test',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
