# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wellcom_app', '0010_auto_20160919_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batt_voltage_mv', models.IntegerField(default=-1)),
                ('batt_percent_charged', models.IntegerField(default=-1)),
                ('adc_voltage_mv', models.IntegerField(default=-1)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('reading_interval_s', models.IntegerField()),
                ('temp_readings_c', models.TextField()),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wellcom_app.Well')),
            ],
        ),
        migrations.RemoveField(
            model_name='deviceinput',
            name='well',
        ),
        migrations.DeleteModel(
            name='DeviceInput',
        ),
    ]
