# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wellcom_app', '0011_auto_20160919_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usage',
            name='date',
        ),
        migrations.RemoveField(
            model_name='usage',
            name='usage_count',
        ),
        migrations.AddField(
            model_name='usage',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
