# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wellcom_app', '0015_auto_20160921_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('usage_count', models.IntegerField()),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wellcom_app.Well')),
            ],
        ),
        migrations.CreateModel(
            name='HourlyUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('usage_count', models.IntegerField()),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wellcom_app.Well')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('usage_count', models.IntegerField()),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wellcom_app.Well')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('usage_count', models.IntegerField()),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wellcom_app.Well')),
            ],
        ),
        migrations.CreateModel(
            name='YearlyUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('usage_count', models.IntegerField()),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wellcom_app.Well')),
            ],
        ),
    ]
