# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellcom_app', '0017_auto_20160922_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='timestamp',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='watertest',
            name='aluminum',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='watertest',
            name='ammonia_nitrogen',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='watertest',
            name='calcium',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='watertest',
            name='calcium_hardness',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='watertest',
            name='chloride',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='watertest',
            name='conductivity_uscm',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='watertest',
            name='copper',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='watertest',
            name='fluoride',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='watertest',
            name='magnesium',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='watertest',
            name='magnesium_hardness',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='watertest',
            name='manganese',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='watertest',
            name='mpn_index_tc_per_deciliter',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='watertest',
            name='nitrate_nitrogen',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='watertest',
            name='nitrite_nitrogen',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='watertest',
            name='pH',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='watertest',
            name='sulphate',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='watertest',
            name='suspended_solids',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='watertest',
            name='total_alkalinity',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='watertest',
            name='total_dissolved_solids',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='watertest',
            name='total_hardness',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='watertest',
            name='total_iron',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='watertest',
            name='total_solids',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='watertest',
            name='turbidity_ntu',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
    ]
