# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellcom_app', '0019_auto_20160926_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='batt_percent_charged',
            field=models.IntegerField(default=77),
            preserve_default=False,
        ),
    ]
