# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 17:41
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils import timezone
from datetime import datetime, timedelta
import random


def add_wells(apps, schema_editor):
    Well = apps.get_model("wellcom_app", "Well")
    Note = apps.get_model("wellcom_app", "Note")
    DeviceData = apps.get_model("wellcom_app", "DeviceData")

    # Create Wells
    test_well = Well(name="Test Well", latitude=35.993078,
                     longitude=-78.904689, country="United States",
                     date_installed="2016-07-11", last_update=timezone.now(),
                     estimated_users=500, cost_usd=8000.50,
                     contractor="Test Contractor", flow_rate_lpm=120)
    test_well.save()

    # For now, just adding test data, so I've commented this out.
    # well = Well(name="Kogadoone", latitude=10.793056,
    #             longitude=-0.928889, country="Ghana",
    #             date_installed="2015-11-22", last_update=timezone.now(),
    #             estimated_users=1000, cost_usd=4000,
    #             contractor="Zaayoka Construction Ltd", flow_rate_lpm=180)
    # well.save()

    # Create Notes
    test_note_one = Note(well=test_well, title="Test note #1 title",
                         text="Test note #1 text")
    test_note_one.save()

    test_note_two = Note(well=test_well, title="Test note #2 title",
                         text="Test note #2 text")
    test_note_two.save()

    # Create DeviceData
    reading_timestamp = datetime(2016, 9, 13)
    for i in range(17280):
        reading_timestamp += timedelta(0, 5)
        # Generating random temperature readings for some testing data
        temp = 29 + random.uniform(-5, 5)
        device_data = DeviceData(well=test_well, timestamp=reading_timestamp,
                                 temperature_c=temp)
        device_data.save()


class Migration(migrations.Migration):

    dependencies = [
        ('wellcom_app', '0003_auto_20160913_0004'),
    ]

    operations = [
        migrations.RunPython(add_wells)
    ]
