# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 18:34
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils import timezone
from datetime import datetime, timedelta
import random


def add_wells(apps, schema_editor):
    Well = apps.get_model("wellcom_app", "Well")

    # Create Wells
    test_well = Well(name="Test Well 2", latitude=36.993078,
                     longitude=-79.904689, country="United States",
                     date_installed="2016-06-20", last_update=timezone.now(),
                     estimated_users=1100, cost_usd=5000,
                     contractor="Test Contractor 2", flow_rate_lpm=160)
    test_well.save()


class Migration(migrations.Migration):

    dependencies = [
        ('wellcom_app', '0004_auto_20160913_1741'),
    ]

    operations = [
        migrations.RunPython(add_wells)
    ]
