# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellcom_app', '0005_auto_20160913_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='depth_m',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
    ]
